apiVersion: v1
kind: PersistentVolume
metadata:
  name: 8bells-vdpi-pv
  namespace: guard-kube
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/8bells-vdpi-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 8bells-vdpi-pv-claim
  namespace: guard-kube
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
